chore: comment out git push command for debugging

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -228,10 +228,10 @@ runs:
                 echo "remote set-url origin ..."
                 git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
                 echo "git push origin $NEW_TAG"
-                git push origin $NEW_TAG || {
-                    echo "::error::Failed to push new tag. Please check if the provided token has sufficient permissions."
-                    exit 1
-                }
+                # git push origin $NEW_TAG || {
+                #     echo "::error::Failed to push new tag. Please check if the provided token has sufficient permissions."
+                #     exit 1
+                # }
                 echo "version=$NEW_TAG" >> $GITHUB_OUTPUT
                 echo "version_full=$VERSION_FULL" >> $GITHUB_OUTPUT
                 echo "version_rpm=$VERSION_RPM" >> $GITHUB_OUTPUT
